### ISSUE TITLE
Can it be used as a node module?

### ISSUE THREAD

**Issue by hristod** [lgraubner/node-sitemap-generator-cli#1]
It would be great if this can be used as a node module. This is exactly what I need, but I need to integrate it into a express application.

**Comment by lgraubner** [comment]
This should be easy to do, the last update seperated the CLI part and the generator itself. But this should not be part of this module. I could think of creating two seperate modules like "sitemap-generator" and "sitemap-generator-cli".
Probably I could look into this in the next couple days. What output should the module have? A string containing the XML-Markup?

**Comment by hristod** [comment]
For me, the best output would be in a JSON format. Maybe with a XML string option? I do not need the module to generate a XML sitemap, but rather to show me the structure of the website so I can visualise it to the user. But I can also parse the XML and get a JSON from it, so no big deal. If it's in a JSON format, it would be much more universal IMO :)

**Comment by lgraubner** [comment]
Well, the purpose of this module is to generate an xml sitemap. You should look into [node-simplecrawler](https://github.com/cgiffard/node-simplecrawler).
