### ISSUE TITLE
Crawling through Google Analytics Script

### ISSUE THREAD

**Issue by sscho** [lgraubner/node-sitemap-generator-cli#2]
Hi,

Firstly, thanks for the neat tool.

I use Google Analytics on my website, and whenever I run the following command:

`
$ sitemap-generator --path=public/code/ code.snipcademy.com
`

I get around 70 errors that are similar to below:

```
Not found: http://code.snipcademy.com/tutorials/data-structures/graphs/g;m.parentNode.insertBefore%28a,m%29
Not found: http://code.snipcademy.com/tutorials/algorithms/g;m.parentNode.insertBefore%28a,m%29
Not found: http://code.snipcademy.com/tutorials/algorithms/sorting/g;m.parentNode.insertBefore%28a,m%29
```

The 'g;m.parentNode.insertBefore%28a,m%29 portion is for sure coming from the Google Analytics javascript. If you could fix this, that'd be great - thanks!

**Comment by lgraubner** [comment]
This has been a bug in the underlying `node-simplecrawler` package. I updated the dependencies and explicitly excluded URLs from `scripts`, as those don't have to be in a sitemap.
I created a new Version (v3.2.0) which should fix your issue. If not please reply here again.

Have a nice day.
