### ISSUE TITLE
allow creating sitemap of subpage

### ISSUE THREAD

**Issue by DennisBecker** [lgraubner/node-sitemap-generator-cli#4]
I want to use a sitemap index and create site maps for subpages. So I tried your tool but if you run it with a deeper link of your website, it ignores the the parameter and just starts to crawl the whole domain.

An example for such a service which allows creating sitemaps of subpages is https://www.xml-sitemaps.com/

There you can run the service against http://www.example.com/foo and it will only generate the sitemap of URLs below /foo

**Comment by lgraubner** [comment]
This behavior is caused by the underlying [crawler](https://github.com/cgiffard/node-simplecrawler). It doesn't care for the hierarchy, it only looks for links. I guess this is possible, will have to look into it.

**Comment by DennisBecker** [comment]
Another issue is, that my subpages I want to crawl are all running with HTTPS only but some parts of the website like the homepage is running on HTTP. At the moment, the tool ignores all pages which use HTTPS (I guess that is the same issue).

**Comment by lgraubner** [comment]
See #3

**Comment by lgraubner** [comment]
Implemented in PR #7
