### ISSUE TITLE
Fetch only resources from anchor tags

### ISSUE THREAD

**Issue by DennisBecker** [lgraubner/node-sitemap-generator-cli#5]
I've seen that there is an exclude map for different file extensions. This works good for a bunch of use cases like removing URLs from img tags.

It would be better to only filter for anchor tags with href attributes. I've seen an example from simplecrawler which uses cheerio to find only those links at https://github.com/cgiffard/node-simplecrawler#link-discovery

**Comment by lgraubner** [comment]
Right, seems more reliable than the "native" way. Feel free to make a pull request. Otherwise I will look into it when I have some spare time. Probably the tests have to be updated as well to work with cheerio.

**Comment by DennisBecker** [comment]
I will have a look, I'm trying to figure out how I can check best against the initial path if given, so that crawling subpages only will work. I've found this because the logging showed up .svg files which are only used in img-tags.

**Comment by lgraubner** [comment]
The list of included file extensions is based on file types Google is able to index. I'm not quite sure which to include and which not.

**Comment by lgraubner** [comment]
Fixed #7

**Comment by lgraubner** [comment]
Added in #6728cf4
